language: c

os:
    - linux

dist: trusty
sudo: required

compiler:
    - clang
    - gcc

before_install:
    - wget https://www.libsdl.org/release/SDL2-2.0.5.tar.gz
    - tar xzf SDL2-2.0.5.tar.gz

install:
    - sudo apt-get install cmake cmake-data -y
    - (cd SDL2-2.0.5 && ./configure && make && sudo make install)

before_script:
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..

script:
    - make
    - test/octaspire-sdl2-utils-test-runner

