language: c
dist: trusty

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get install libsdl2-dev libsdl2-image-dev cmake cmake-data -y

before_script:
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..

script:
    - make
    - test/octaspire-sdl2-utils-test-runner

