language: c
dist: trusty

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get install libsdl2-dev libsdl2-image-dev cmake cmake-data -y

before_script:
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DOCTASPIRE_SDL2_UTILS_COVERAGE:BOOL=ON ..

script:
    - make
    - test/octaspire-sdl2-utils-test-runner
    - cd test/CMakeFiles/octaspire-sdl2-utils-test-runner.dir
    - gcov *.gcno

after_success:
      - bash <(curl -s https://codecov.io/bash)

